SELECT DISTINCT flidarid FROM [dbo].[rwind]
DECLARE @ID VARCHAR(20)
SELECT @ID = FLIDARID FROM (SELECT DISTINCT FLIDARID FROM [dbo].[rwind]) AS F
DECLARE @STARTDATE DATETIME
SELECT @STARTDATE = MAX(datetimekey) FROM [dbo].[rwind] GROUP BY flidarid
DECLARE @ENDDATE DATETIME
SELECT @ENDDATE = MIN(datetimekey) FROM [dbo].[rwind] GROUP BY flidarid
 
IF EXISTS (SELECT flidarid FROM [dbo].[rwind] WHERE FLIDARID = @ID)
BEGIN
    SET @STARTDATE = DATEADD(MINUTE, 10, @STARTDATE)
END

